### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by gknocke** [Javex/libscep#71] opened 2015-07-29 10:08 UTC
We need to include much more SCEPE objects. A program that executes this library may need more differentiated errors. In my case, SCEPE_INVALID_CONTENT was less helpful than something like SCEPE_INVALID_CONTENT_NO_CHALLENGE_PW

**Comment by Javex** [comment] 2015-07-29 10:10
Duplicate of #20

**Closed as completed by Javex** 2015-07-29 10:10 UTC
Labels: duplicate
